name: Build, Patch and Release
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "ver/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --no-daemon --stacktrace
      - name: Build Reobf Jar (Default)
        run: ./gradlew createReobfPaperclipJar --no-daemon --stacktrace
      - name: Build Mojmap Jar
        run: ./gradlew createMojmapPaperclipJar --no-daemon --stacktrace
      - name: Rebuild on Failure
        if: ${{ failure() }}
        run: |
          ./gradlew clean cleanCache
          ./gradlew applyPatches --no-daemon --stacktrace
          ./gradlew createReobfPaperclipJar --no-daemon --stacktrace
          ./gradlew createMojmapPaperclipJar --no-daemon --stacktrace
          ./gradlew generateDevelopmentBundle --no-daemon --stacktrace
          